// NATSInternal.Frontend/NATSInternal.React/src/components/form/Input.tsx
import React, { useContext } from "react";
import { FormFieldContext } from "./FormField";

// Props.
type InputProps = { render: (className?: string, path?: string, displayName?: string) => React.ReactNode };

// Component.
export default function Input(props: InputProps) {
  // Dependencies.
  const context = useContext(FormFieldContext);

  // Template.
  return props.render(undefined, context?.path, context?.displayName);
}

// NATSInternal.Frontend/src/components/form/Input.tsx
import { useContext } from "solid-js";
import { FormFieldContext } from "./FormField";

// Props.
type InputProps = { render: (getClassName: () => string | undefined) => JSX.Element };

// Component.
export default function Input(props: InputProps) {
  // Context.
  const formFieldPayload = useContext(FormFieldContext);

  // Computed.
  const computeClassName = () => {
    if (!formFieldPayload || !formFieldPayload?.isValidated) {
      return;
    }

    return formFieldPayload.hasError ? "invalid" : "valid";
  };

  return props.render(computeClassName);
}
