// NATSInternal.React/src/components/form/FormField.tsx
import React, { useMemo, createContext, useContext } from "react";
import { useTsxHelper } from "@/helpers";

// Shared components.
import { FormContext } from "@/components/form/Form";

// Context.
export type FormFieldContextPayload = { isValidated: boolean; hasError: boolean; };
export const FormFieldContext = createContext<FormFieldContextPayload>(undefined!);

// Props.
export type FormFieldProps = {
  label?: string;
  propertyPath?: string;
  children: React.ReactNode;
} & React.ComponentPropsWithoutRef<"div">;

// Components.
export default function FormField(props: FormFieldProps) {
  // Dependencies.
  const formContext = useContext(FormContext);
  const { joinClassName } = useTsxHelper();

  // Computed.
  const errorMessage = useMemo(() => {
    console.log("Triggered");
    if (formContext && props.propertyPath) {
      const messages = formContext.errorCollection.details
        .filter(d => d.propertyPath === props.propertyPath)
        .map(d => d.message);

      return messages.length >= 1 ? messages[0] : undefined;
    }
  }, [formContext.errorCollection.details]);

  const contextPayload = useMemo<FormFieldContextPayload>(() => ({
    isValidated: !!formContext.errorCollection.isValidated,
    hasError: !!errorMessage
  }), [formContext.errorCollection.details]);

  return (
    <div className={joinClassName("form-group", props.className)}>
      <pre>{JSON.stringify(formContext?.errorCollection.details, null, 2)}</pre>
      {/* Label */}
      {props.label && <label className="form-label">{props.label}</label>}

      {/* Input */}
      <FormFieldContext.Provider value={contextPayload}>
        {props.children}
      </FormFieldContext.Provider>

      {/* Message */}
      {!!errorMessage && <span className="text-danger">{errorMessage}</span>}
    </div>
  );
}

// NATSInternal.Frontend/NATSInternal.Solid/src/components/form/FormField.tsx
import { createContext, useContext, Show } from "solid-js";
import { useTsxHelper } from "@/helpers";

// Shared components.
import { FormContext } from "@/components/form/Form";

// Context.
export type FormFieldContextPayload = { isValidated: boolean; hasError: boolean; };
export const FormFieldContext = createContext<FormFieldContextPayload>();

// Props.
export type FormFieldProps = {
  label?: string;
  propertyPath?: string;
  children: JSX.Element;
} & JSX.IntrinsicElements["div"];

// Components.
export default function FormField(props: FormFieldProps) {
  // Dependencies.
  const formContext = useContext(FormContext);
  const { joinClassName } = useTsxHelper();

  // Computed states.
  function computeErrorMessage(): string | undefined {
    console.log("Triggered");
    if (formContext && props.propertyPath) {
      const messages = formContext.getErrorCollection().details
        .filter(d => d.propertyPath === props.propertyPath)
        .map(d => d.message);

      return messages.length >= 1 ? messages[0] : undefined;
    }
  }

  function computeHasErrorMessage(): boolean {
    return !!computeErrorMessage();
  }

  return (
    <div class={joinClassName("form-group", props.class)}>
      <pre>{JSON.stringify(formContext?.getErrorCollection().details, null, 2)}</pre>
      {/* Label */}
      <Show when={props.label}>
        <label class="form-label">{props.label}</label>
      </Show>

      {/* Input */}
      <FormFieldContext.Provider value={{
        isValidated: !!formContext?.getErrorCollection?.().isValidated,
        get hasError() {
          return computeHasErrorMessage();
        }
      }}>
        {props.children}
      </FormFieldContext.Provider>

      {/* Message */}
      <Show when={computeHasErrorMessage()}>
        <span class="text-danger">{computeErrorMessage()}</span>
      </Show>
    </div>
  );
}
