// NATSInternal.Frontend/NATSInternal.React/src/components/form/FormField.tsx
import React, { useMemo, createContext, useContext } from "react";
import { getDisplayName } from "@/metadata";
import { joinClassName, compute } from "@/helpers";

// Shared components.
import { FormContext } from "@/components/form/Form";

// Context.
export type FormFieldContextPayload = {
  isValidated: boolean;
  hasError: boolean;
  path?: string;
  displayName?: string
};

export const FormFieldContext = createContext<FormFieldContextPayload | null>(null);

// Props.
export type FormFieldProps = {
  path?: string;
  displayName?: string;
  children: React.ReactNode;
} & React.ComponentPropsWithoutRef<"div">;

// Components.
export default function FormField(props: FormFieldProps) {
  // Dependencies.
  const formContext = useContext(FormContext);

  // Computed.
  const errorMessage = useMemo(() => {
    if (!formContext || !formContext.errorCollection.isValidated || !props.path) {
      return;
    }

    const messages = formContext.errorCollection.details
      .filter(d => d.propertyPath === props.path)
      .map(d => d.message);

    if (messages.length === 0) {
      return;
    }

    return messages[0];
  }, [formContext?.errorCollection.details]);

  const displayName = useMemo(() => {
    if (props.displayName) {
      return props.displayName;
    }

    if (!props.path) {
      return;
    }
    
    const pathElements = props.path.split(".");
    if (pathElements.length === 0) {
      return;
    }

    const lastIndexerOmittedPathElement = pathElements[pathElements.length - 1].replace(/\[[0-9]]/g, "");
    return getDisplayName(lastIndexerOmittedPathElement);
  }, []);

  const validationMessageClassName = compute<string | undefined>(() => {
    if (formContext?.errorCollection.isValidated) {
      if (errorMessage) {
        return "field-validation-error";
      }

      return "field-validation-valid";
    }
  });

  const contextPayload = useMemo<FormFieldContextPayload>(() => {
    return {
      isValidated: !!formContext?.errorCollection.isValidated,
      hasError: !!errorMessage,
      path: props.path,
      displayName: displayName ?? undefined
    };
  }, [formContext?.errorCollection.details, displayName]);

  // Template.
  return (
    <div className={joinClassName(
      props.className,
      "form-field flex flex-col justify-stretched",
    )}>
      {/* Label */}
      {displayName && (
        <label htmlFor={props.path}>
          {displayName}
        </label>
      )}

      {/* Input */}
      <FormFieldContext.Provider value={contextPayload}>
        {props.children}
      </FormFieldContext.Provider>

      {/* Message */}
      <span className={validationMessageClassName}>
        {errorMessage}
      </span>
    </div>
  );
}

// NATSInternal.Frontend/NATSInternal.Svelte/src/components/form/FormField.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import type { HTMLAttributes } from "svelte/elements";
import { getDisplayName } from "@/metadata";
import { getFormContext } from "./Form.svelte";
import { setFormFieldContext } from "./FormField";

// Props.
const props: {
  path?: string;
  displayName?:
  string; children: Snippet
} & HTMLAttributes<HTMLDivElement> = $props();
const formContextPayload = getFormContext();

// Computed.
const errorMessage = $derived.by(() => {
  if (!formContextPayload || !formContextPayload.errorCollection.isValidated || !props.path) {
    return;
  }

  const messages = formContextPayload.errorCollection.details
    .filter(d => d.propertyPath === props.path)
    .map(d => d.message);

  if (messages.length === 0) {
    return;
  }

  return messages[0];
});

const displayName = $derived.by(() => {
  if (props.displayName) {
    return props.displayName;
  }

  if (!props.path) {
    return;
  }

  const pathElements = props.path.split(".");
  if (pathElements.length === 0) {
    return;
  }

  const lastIndexerOmittedPathElement = pathElements[pathElements.length - 1].replace(/\[[0-9]]/g, "");
  return getDisplayName(lastIndexerOmittedPathElement) ?? undefined;
});

const validationMessageClassName = $derived.by<string | undefined>(() => {
  if (formContextPayload?.errorCollection.isValidated) {
    if (errorMessage) {
      return "field-validation-error";
    }

    return "field-validation-valid";
  }
});

setFormFieldContext({
  get isValidated(): boolean {
    return formContextPayload?.errorCollection.isValidated;
  },
  get hasError(): boolean {
    return !!errorMessage;
  },
  get path(): string | undefined {
    return props.path;
  },
  get displayName(): string | undefined {
    return props.displayName;
  }
});
</script>

<div class="form-field flex flex-col justify-stretched">
  {!!errorMessage}

  {#if displayName}
    <label for={props.path}>
      {displayName}
    </label>
  {/if}

  {@render props.children?.()}
</div>
