// NATSInternal.Frontend/NATSInternal.React/src/components/layouts/MainPageLayout.tsx
import React, { useState, useMemo, useEffect, Fragment } from "react";
import { useMatches, Outlet, Link, useNavigation, useNavigate } from "react-router";
import { useAuthenticationStore, useNavigationBarStore } from "@/stores";
import { useMatchedRouteHandles } from "@/hooks";
import { joinClassName, compute, getSignInRoutePath } from "@/helpers";

// Child components.
import { HomeIcon, ChevronRightIcon } from "@heroicons/react/24/solid";

// Props.
type BreadcrumbItemData = { pageTitle: string | null; breadcrumbTitle: string; routePath: string | null };

// Components.
export default function MainPageLayout(): React.ReactNode {
  // Dependencies.
  const navigation = useNavigation();
  const navigate = useNavigate();
  const isAuthenticated = useAuthenticationStore(store => store.isAuthenticated);
  const isNavigationBarExpanded = useNavigationBarStore(store => store.isExpanded);

  // Dependencies.
  const matchedRouteHandlesArray = useMatchedRouteHandles();

  // States.
  const [shouldBlockPointerEvent, setShouldBlockPointerEvent] = useState<boolean>(() => false);

  // Computed.
  const isNavigating = compute<boolean>(() => Boolean(navigation.location));
  const matchedRouteHandle = compute<RouteHandle | null>(() => {
    if (!matchedRouteHandlesArray.length) {
      return null;
    }

    return matchedRouteHandlesArray[matchedRouteHandlesArray.length - 1];
  });

  // Effect.
  useEffect(() => {
    if (!isAuthenticated) {
      navigate(getSignInRoutePath());
    }
  }, []);

  useEffect(() => {
    setTimeout(() => setShouldBlockPointerEvent(isNavigationBarExpanded), 200);
  }, [isNavigationBarExpanded]);

  // Template.
  if (!isAuthenticated) {
    return null;
  }

  return (
    <div
      id="main-page-layout"
      className={joinClassName(
        "transition-opacity",
        isNavigating && "opacity-50 navigating",
        shouldBlockPointerEvent && "pointer-events-none"
      )}
    >
      {/* The bar on top the current page, containing breadcrumb */}
      <div id="breadcrumb">
        <Breadcrumb />
      </div>

      <div id="page-title-container">
        <span className="text-2xl">{matchedRouteHandle?.pageTitle}</span>
        <span className="text-md opacity-50">{matchedRouteHandle?.description}</span>
      </div>

      {/* Page */}
      <Outlet />
    </div>
  );
}

function Breadcrumb(): React.ReactNode {
  // Dependencies.
  const matchedRoutes = useMatches();

  // Computed.
  const breadcrumItems = useMemo<BreadcrumbItemData[]>(() => {
    const items: { pageTitle: string | null; breadcrumbTitle: string; routePath: string | null }[] = [];
    for (const matchRoute of matchedRoutes) {
      const handle = matchRoute.handle;
      if (typeof handle === "object" && handle != null && "breadcrumbTitle" in handle) {
        const breadcrumbTitle = handle["breadcrumbTitle" as keyof typeof handle] as string;
        const pageTitle = (handle["pageTitle" as keyof typeof handle] as string) ?? null;
        items.push({ pageTitle, breadcrumbTitle, routePath: matchRoute.pathname });
      }
    }

    return items;
  }, [matchedRoutes]);

  // Template.
  return (
    <div className="flex flex-wrap gap-3 items-center ms-2 lg:ms-3 translate-y-[7.5%] h-8">
      {breadcrumItems.map((item, index) => (
        <Fragment key={index}>
          <BreadcrumbItem {...item} isFirst={index === 0} isLast={index === breadcrumItems.length - 1} />
          {index < breadcrumItems.length - 1 && (
            <ChevronRightIcon
              className={joinClassName("size-4", index !== 0 && "hidden sm:inline")}
              key={index}
            />
          )}
        </Fragment>
      ))}
    </div>
  );
}

function BreadcrumbItem(props: BreadcrumbItemData & { isFirst: boolean, isLast: boolean; }): React.ReactNode {
  // Template.
  function renderChild(): React.ReactNode {
    if (props.isFirst) {
      return <HomeIcon className="size-5" />;
    }
    
    if (props.isLast) {
      return (
        <>
          <span className="hidden sm:inline">{props.breadcrumbTitle}</span>
          <span className="text-lg inline sm:hidden">{props.pageTitle}</span>
        </>
      );
    }

    return <span className="hidden sm:inline">{props.breadcrumbTitle}</span>;
  };

  return (
    <Link
      to={props.routePath ?? ""}
      className={joinClassName(
        (!props.isFirst && !props.isLast) ? "hidden sm:inline" : "text-lg sm:text-base",
        (props.routePath == null || props.isLast) && "pointer-events-none"
      )}
    >
      {renderChild()}
    </Link>
  );
}

// NATSInternal.Frontend/NATSInternal.Vue/src/components/layouts/MainPageLayout.vue
<script lang="ts">
import type { RouteLocationRaw } from "vue-router";

type BreadcrumbItemData = { pageTitle: string | null; text: string; to: RouteLocationRaw | null };
</script>

<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { useRoute, RouterView, RouterLink } from "vue-router";
import { useNavigationBarStore } from "@/stores";
import { createReusableTemplate, useTitle } from "@vueuse/core";

// Child components.
import { HomeIcon, ChevronRightIcon } from "@heroicons/vue/24/solid";

// Dependencies.
const route = useRoute();
const navigationBarStore = useNavigationBarStore();
const pageTitle = useTitle();

// States.
const shouldBlockPointerEvent = ref(false);

// Computed.
const breadcrumItemsData = computed<BreadcrumbItemData[]>(() => {
  return route.matched
    .filter((matchedRoute) => matchedRoute.meta.breadcrumbItem)
    .map<BreadcrumbItemData>((matchedRoute) => {
      const breadcrumbItem = typeof matchedRoute.meta.breadcrumbItem === "function"
        ? matchedRoute.meta.breadcrumbItem(route)
        : matchedRoute.meta.breadcrumbItem;

      return {
        pageTitle: matchedRoute.meta.pageTitle ?? null,
        text: breadcrumbItem.text,
        to: breadcrumbItem.to
      };
    });
});

const className = computed<string | undefined>(() => shouldBlockPointerEvent.value ? "pointer-events-none" : undefined);

const computeItemClassName = (to: RouteLocationRaw | null, isFirst: boolean, isLast: boolean): string | null => {
  const names: string[] = [];
  if (!isFirst && !isLast) {
    names.push("hidden sm:inline");
  } else {
    names.push("text-lg sm:text-base");
  }

  if (to == null || isLast) {
    names.push("pointer-events-none");
  }

  return names.length === 0 ? null : names.join(" ");
};

const computeSeparatorIconClassName = (index: number): string => {
  const names: string[] = ["size-4"];
  if (index) {
    names.push("hidden sm:inline");
  }

  return names.join(" ");
};

// Life cycle hooks.
watch(() => navigationBarStore.isExpanded, () => {
  setTimeout(() => shouldBlockPointerEvent.value = navigationBarStore.isExpanded, 200);
});

// Template.
const [BreadcrumbItemDefinition, BreadcrumbItem] = createReusableTemplate<{
  data: BreadcrumbItemData;
  isFirst: boolean;
  isLast: boolean;
}>();
</script>

<template>
  <div id="main-page-layout" v-bind:class="className">
    <div id="breadcrumb">
      <BreadcrumbItemDefinition v-slot="{ data: { to, text }, isFirst, isLast }">
        <RouterLink
          v-bind:class="computeItemClassName(to, isFirst, isLast)"
          v-bind:to="to ?? { name: `home` }"
        >
          <HomeIcon v-if="isFirst" class="size-5" />
          <template v-else-if="isLast">
            <span class="hidden sm:inline">{{ text }}</span>
            <span class="text-lg inline sm:hidden">{{ pageTitle }}</span>
          </template>
          <span v-else class="hidden sm:inline">{{ text }}</span>
        </RouterLink>
      </BreadcrumbItemDefinition>

      <div class="flex flex-wrap gap-3 items-center ms-2 lg:ms-3 translate-y-[7.5%] h-8">
        <template v-for="(data, index) of breadcrumItemsData" v-bind:key="index">
          <BreadcrumbItem
            v-bind:data="data"
            v-bind:is-first="index === 0"
            v-bind:is-last="index === breadcrumItemsData.length - 1"
          />
          <ChevronRightIcon
            v-if="index < breadcrumItemsData.length - 1"
            v-bind:class="computeSeparatorIconClassName(index)"
          />
        </template>
      </div>
    </div>
    
    <div id="page-title-container">
        <span class="text-2xl">{{ route.meta.pageTitle }}</span>
        <span class="text-md opacity-50">{{ route.meta.description }}</span>
    </div>

    <RouterView v-slot="{ Component }">
      <Transition name="fade" mode="out-in">
        <Suspense>
          <component v-bind:is="Component" />
        </Suspense>
      </Transition>
    </RouterView>
  </div>
</template>
