// NATSInternal.Frontend/NATSInternal.Vue/src/pages/authentication/SignInPage.vue
<script setup lang="ts">
import { reactive } from "vue";
import { useRouter } from "vue-router";
import { useApi, ConnectionError, InternalServerError } from "@/api";
import { createSignInModel } from "@/models";
import { useAuthenticationStore } from "@/stores";

// Child components.
import { Form, FormField } from "@/components/form";
import { ExclamationCircleIcon } from "@heroicons/vue/24/solid";

// Dependencies.
const router = useRouter();
const api = useApi();
const authenticationStore = useAuthenticationStore();

// States.
const states = reactive({
  model: createSignInModel(),
  commonError: null as string | null,
  isSignedIn: false,
  isInitiallyChecking: false,
  isSubmitting: false,
});

// Computed.
const computeSignInClassName = (isValidated: boolean, isValid: boolean) => {
  return ["btn", isValidated && !isValid && "btn-danger"];
};

// Callbacks.
const signInAsync = async (): Promise<void> => {
  states.isSubmitting = true;
  states.commonError = null;
  
  try {
    await api.authentication.getAccessCookieAsync(states.model.toRequestDto());
  } finally {
    states.model.password = "";
    states.isSubmitting = false;
  }
};

const handleSignInSucceeded = (): void => {
  states.isSignedIn = true;
  authenticationStore.isAuthenticated = true;
  setTimeout(() => router.push({ name: "home" }), 0);
};

const handleSignInFailed = (error: Error, errorHandled: boolean): void => {
  if (errorHandled) {
    return;
  }

  states.isSignedIn = false;
  if (error instanceof InternalServerError) {
    states.commonError = "Đã xảy ra lỗi từ máy chủ.";
  } else if (error instanceof ConnectionError) {
    states.commonError = "Không thể kết nối đến máy chủ.";
  } else {
    states.commonError = "Đã xảy ra lỗi không xác định.";
  }
};
</script>

<template>
  <div class="form-container">
    <Transition name="fade" mode="out-in">
      <Form
        v-if="!states.isSignedIn"
        v-bind:upsert-action="signInAsync"
        v-on:upserting-succeeded="handleSignInSucceeded"
        v-on:upserting-failed="handleSignInFailed"
        v-slot="{ errorCollection: { isValid, isValidated } }"
        class="form"
      >
        <!-- Introduction -->
        <div class="flex flex-col mb-5">
          <span class="text-4xl font-bold">Đăng nhập</span>
          <span class="text-lg">
              Chào mừng bạn đã quay trở lại.
            </span>
        </div>

        <!-- UserName -->
        <FormField class="mb-3" path="userName">
          <input
            v-model="states.model.userName"
            type="text"
            class="form-control"
            placeholder="Tên tài khoản"
            autocapitalize="off"
          />
        </FormField>
        
        <!-- Password -->
        <FormField class="mb-3" path="password">
          <input
            v-model="states.model.password"
            type="password"
            class="form-control"
            placeholder="Mật khẩu"
          />
        </FormField>

        <!-- Button -->
        <button v-bind:class="computeSignInClassName(isValidated, isValid)" type="submit">
          <span v-if="states.isSubmitting">Đang kiểm tra</span>
          <span v-else-if="!isValid">Đăng nhập lại</span>
          <span v-else>Đăng nhập</span>
        </button>

        <!-- Common error -->
        <span v-if="states.commonError" class="alert alert-red-outline flex justify-center mt-3 w-full">
          <ExclamationCircleIcon class="size-5" />
          {{ states.commonError }}
        </span>
      </Form>

      <div v-else class="successful-notification">
        Đăng nhập thành công
      </div>
    </Transition>

    <div class="copyright">
      © {{ new Date().getFullYear() }} - Bản quyền thuộc về Ngô Khánh Huy
    </div>
  </div>
</template>

<style scoped>
@import "@/assets/css/style.css" reference;

.form-container {
  @apply 
    bg-white dark:bg-neutral-900 sm:bg-transparent dark:sm:bg-transparent
    flex flex-col justify-start items-center w-screen h-screen pt-[25vh];
}

.form {
  @apply 
    bg-white dark:bg-neutral-900
    border border-transparent sm:border-black/15 dark:sm:border-white/15
    shadow-none sm:shadow-xs
    flex flex-col rounded-xl p-8 items-stretch w-87.5 relative;
}

.successful-notification {
  @apply
    bg-emerald-500/10 border border-emerald-500/50
    flex justify-center items-center w-87.5 relative rounded-xl p-8 shadow-none sm:shadow-xs
    text-emerald-700 dark:text-emerald-400 uppercase font-bold;
}

.copyright {
  @apply text-primary/50 absolute bottom-1 sm:relative sm:bottom-[unset] flex justify-end mb-3 sm:mt-10 sm:mb-0;
}
</style>

// NATSInternal.Frontend/NATSInternal.React/src/pages/authentication/signIn/SignInPage.tsx
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import { useApi, ConnectionError, InternalServerError } from "@/api";
import { createSignInModel } from "@/models";
import { useAuthenticationStore } from "@/stores";
import { useTsxHelper, useRouteHelper } from "@/helpers";

// Child components.
import { Form, FormField, TextInput } from "@/components/form";
import { Button } from "@/components/ui";

// Components.
export default function SignInPage(): React.ReactNode {
  // Dependencies.
  const navigate = useNavigate();
  const api = useApi();
  const authenticationStore = useAuthenticationStore();
  const { compute, joinClassName } = useTsxHelper();
  const { getHomeRoutePath } = useRouteHelper();

  // Model and state.
  const [model, setModel] = useState(createSignInModel);
  const [state, setState] = useState(() => ({
    commonError: null as string | null,
    isSignedIn: false,
    isInitiallyChecking: false,
    isSubmitting: false,
    hasModelError: false,
  }));

  // Effect.
  useEffect(() => {
    if (authenticationStore.isAuthenticated) {
      navigate(getHomeRoutePath());
    }
  }, []);

  // Computed.
  const areRequiredFieldsFilled = compute<boolean>(() => {
    return model.userName.length > 0 && model.password.length > 0;
  });

  const buttonText = compute<string>(() => {
    if (state.isSubmitting) {
      return "Đang kiểm tra";
    } else if (state.hasModelError) {
      return "Đăng nhập lại";
    } else {
      return "Đăng nhập";
    }
  });

  const buttonVariant = compute<ColorVariant>(() => state.hasModelError ? "danger" : "primary");

  // Callbacks.
  async function loginAsync(): Promise<void> {
    setState((state) => ({
      ...state,
      isSubmitting: true,
      commonError: null,
      hasModelError: false,
    }));

    try {
      await api.authentication.getAccessCookieAsync(model.toRequestDto());
    } finally {
        setModel(model => ({ ...model, password: "" }));
        setState(state => ({ ...state, isSubmitting: false }));
    }
  }

  function handleLoginSucceeded(): void {
    setState(state => ({ ...state, isSignedIn: true }));
    authenticationStore.setIsAuthenticated(true);
    setTimeout(() => {
      navigate(getHomeRoutePath());
    }, 0);
  }

  function handleLoginFailed(error: Error, errorHandled: boolean): void {
    if (errorHandled) {
      setState(s => ({ ...s, hasModelError: true }));
      return;
    }

    let commonError: string;
    if (error instanceof InternalServerError) {
      commonError = "Đã xảy ra lỗi từ máy chủ.";
    } else if (error instanceof ConnectionError) {
      commonError = "Không thể kết nối đến máy chủ.";
    } else {
      commonError = "Đã xảy ra lỗi không xác định.";
    }

    setState(state => ({
      ...state,
      commonError,
      isSignedIn: false
    }));
  }

  async function handleEnterKeyPressedAsync(): Promise<void> {
    if (!state.isSignedIn && areRequiredFieldsFilled) {
      await loginAsync();
    }
  }

  // Template.
  const renderSignInContent = () => (
    <Form
      className={joinClassName(
        "bg-white dark:bg-neutral-900",
        "border border-transparent sm:border-black/15 dark:sm:border-white/15",
        "shadow-none sm:shadow-xs",
        "flex flex-col rounded-xl p-8 items-stretch w-[350px] relative",
      )}
      upsertAction={loginAsync}
      onUpsertingSucceeded={handleLoginSucceeded}
      onUpsertingFailed={handleLoginFailed}
    >
      {/* Introduction */}
      <div className="flex flex-col mb-5">
        <span className="text-4xl font-bold">Đăng nhập</span>
        <span className="text-lg">
            Chào mừng bạn đã quay trở lại.
          </span>
      </div>

      {/* Username */}
      <FormField className="mb-3" path="userName">
        <TextInput
          autoCapitalize="off"
          value={model.userName}
          onValueChanged={(userName) => setModel(model => ({ ...model, userName: userName.toLowerCase() }))}
        />
      </FormField>

      {/* Password */}
      <FormField className="mb-5" path="password">
        <TextInput
          type="password"
          value={model.password}
          onValueChanged={(password) => setModel(model => ({ ...model, password }))}
        />
      </FormField>

      {/* Button */}
      <Button type="submit" className={buttonVariant} showSpinner={state.isSubmitting}>
        {buttonText}
      </Button>

      {/* CommonError */}
      {state.commonError && (
        <span className="alert alert-danger d-flex justify-content-center mt-3 w-100">
            <i className="bi bi-exclamation-triangle-fill me-1" />
          {state.commonError}
        </span>
      )}
    </Form>
  );

  const renderSignedSuccessfullyContent = () => (
    <div className={joinClassName(
      "bg-emerald-500/10 border border-emerald-500/50",
      "flex justify-center items-center w-[350px] relative rounded-xl p-8 shadow-none sm:shadow-xs",
      "text-emerald-700 dark:text-emerald-400 uppercase font-bold")}
    >
      Đăng nhập thành công
    </div>
  );

  return (
    <div
      className={joinClassName(
        "bg-white dark:bg-neutral-900 sm:bg-transparent dark:sm:bg-transparent",
        "flex flex-col justify-start items-center w-screen h-screen pt-[25vh]"
      )}
      onKeyUp={(event) => event.key === "Enter" && handleEnterKeyPressedAsync()}
    >
      {!state.isSignedIn ? renderSignInContent() : renderSignedSuccessfullyContent()}

      <div className={joinClassName(
        "text-primary/50 absolute bottom-1 sm:relative sm:bottom-unset",
        "flex justify-end mb-3 sm:mt-7 sm:mb-0")}
      >
        © {new Date().getFullYear()} - Bản quyền thuộc về Ngô Khánh Huy
      </div>
    </div>
  );
}
