// NATSInternal.Frontend/NATSInternal.Svelte/src/components/form/Form.svelte
<script lang="ts" module>
import { createContext, type Snippet } from "svelte";
import type { HTMLFormAttributes } from "svelte/elements";

export type SubmissionState = "notSubmitting" | "submitting" | "submissionSucceeded";
export type FormContextPayload = {
  errorCollection: ErrorCollectionModel;
  submissionState: SubmissionState;
  handleDeletionAsync?(): Promise<void>;
  isModelDirty?: boolean;
};

const [getFormContext, setFormContext] = createContext<FormContextPayload>();
export { getFormContext };
</script>

<script lang="ts" generics="TUpsertResult">
import { ValidationError, OperationError } from "@/api";
import { createErrorCollectionModel } from "@/models";

// Props.
let props: {
  upsertAction: () => Promise<TUpsertResult>;
  onUpsertingSucceeded?: (result: TUpsertResult) => any;
  onUpsertingFailed?: (error: Error, errorHandled: boolean) => any;
  isModelDirty?: boolean;
  children: Snippet;
} & HTMLFormAttributes = $props();

// States.
const states = $state<FormContextPayload>({
  errorCollection: createErrorCollectionModel(),
  submissionState: "notSubmitting"
});

// Computed.
const className = $derived.by<any[]>(() => {
  return [
    states.submissionState === "submitting" && "opacity-50 pointer-events-none",
    "transition transition-500",
    states.submissionState === "submitting" && "cursor-wait"
  ];
});

// Callbacks.
async function handleUpsertingAsync(event: Event): Promise<void> {
  event.preventDefault();
  states.errorCollection.clear();
  states.submissionState = "submitting";

  try {
    const result = await props.upsertAction();
    props.onUpsertingSucceeded?.(result);
    states.submissionState = "submissionSucceeded";
  } catch (error) {
    states.submissionState = "notSubmitting";
    if (error instanceof ValidationError || error instanceof OperationError) {
      states.errorCollection.mapFromApiErrorDetails(error.errors);
      props.onUpsertingFailed?.(error, true);
      return;
    }

    props.onUpsertingFailed?.(error as Error, false);
    throw error;
  }
}

// Context.
setFormContext(states);
</script>

<form class={className} onsubmit={handleUpsertingAsync} novalidate>
  {@render props.children()}
</form>

// NATSInternal.Frontend/NATSInternal.React/src/components/form/Form.tsx
import React, { useState, useMemo, createContext } from "react";
import { ValidationError, OperationError } from "@/api";
import { createErrorCollectionModel } from "@/models";
import { joinClassName, compute } from "@/helpers";

// Type.
export type SubmissionState = "notSubmitting" | "submitting" | "submissionSucceeded";

// Payload.
type FormContextPayload = {
  errorCollection: ErrorCollectionModel;
  submissionState: SubmissionState;
  isModelDirty?: boolean;
};

// Context.
export const FormContext = createContext<FormContextPayload | null>(null);

// Props.
type FormProps<TUpsertResult> = {
  upsertAction: () => Promise<TUpsertResult>;
  onUpsertingSucceeded?: (result: TUpsertResult) => any;
  onUpsertingFailed?: (error: Error, errorHandled: boolean) => any;
  isModelDirty?: boolean;
} & React.ComponentPropsWithoutRef<"form">;

// Component.
export default function Form<TUpsertResult>(props: FormProps<TUpsertResult>) {
  // Props.
  const { upsertAction, onUpsertingSucceeded, onUpsertingFailed, isModelDirty, ...domProps } = props;

  // States.
  const [errorCollection, setErrorCollection] = useState(createErrorCollectionModel);
  const [submissionState, setSubmissionState] = useState<SubmissionState>("notSubmitting");

  // Computed.
  const submittingClassName = compute(() => {
    if (submissionState === "submitting") {
      return "opacity-50 pointer-events-none";
    }
  });
  
  const contextValue = useMemo<FormContextPayload>(() => {
    return {
      errorCollection,
      submissionState,
      isModelDirty
    };
  }, [errorCollection, submissionState, isModelDirty]);

  // Callbacks.
  async function handleUpsertingAsync(event: React.FormEvent): Promise<void> {
    event.preventDefault();
    setErrorCollection(errorCollection => errorCollection.clear());
    setSubmissionState("submitting");

    try {
      const result = await upsertAction();
      onUpsertingSucceeded?.(result);
      setSubmissionState("submissionSucceeded");
    } catch (error) {
      setSubmissionState("notSubmitting");
      if (error instanceof ValidationError || error instanceof OperationError) {
        setErrorCollection(errorCollection => errorCollection.mapFromApiErrorDetails(error.errors));
        onUpsertingFailed?.(error, true);
        return;
      }

      onUpsertingFailed?.(error as Error, false);
      throw error;
    }
  }

  // Template.
  return (
    <FormContext.Provider value={contextValue}>
      <form
        {...domProps}
        className={joinClassName(
          domProps.className,
          submittingClassName,
          "transition transition-500",
          submissionState === "submitting" && "cursor-wait"
        )}
        noValidate
        onSubmit={handleUpsertingAsync}
      >
        {domProps.children}
      </form>
    </FormContext.Provider>
  );
}
