// NATSInternal.Frontend/NATSInternal.Vue/src/components/form/TextInput.vue
<script setup lang="ts">
// Child components.
import Input from "./Input.vue";

// Props and model.
const props = withDefaults(defineProps<{
  type?: "text" | "password" | "tel" | "email";
}>(), {
  type: "text"
});

const model = defineModel<string>({ required: true });
</script>

<template>
  <Input v-slot="{ className, path, displayName }">
    <input
      v-bind:type="props.type"
      v-bind:class="className"
      v-bind:path="path"
      v-bind:placeholder="displayName"
      v-model="model"
    />
  </Input>
</template>

// NATSInternal.Frontend/NATSInternal.React/src/components/form/TextInput.tsx
import { joinClassName } from "@/helpers";
import Input from "./Input";

// Props.
export type TextInputProps = {
  type?: "text" | "password" | "tel" | "email"
  value: string;
  onValueChanged(newValue: string): any;
} & Omit<React.ComponentPropsWithoutRef<"input">, "type">;

// Component.
export default function TextInput(props: TextInputProps) {
  // Props.
  const { value, onValueChanged, ...domProps } = props;

  // Template.
  function renderInput(className?: string, path?: string, displayName?: string) {
    return (
      <input
        {...domProps}
        name={path}
        className={joinClassName(className, props.className)}
        placeholder={props.placeholder ?? displayName}
        value={value}
        onInput={(event) => onValueChanged((event.target as HTMLInputElement).value)}
      />
    );
  }

  return <Input render={renderInput} />;
}
