// NATSInternal.Frontend/NATSInternal.React/src/components/form/Input.tsx
import React, { useContext } from "react";
import { FormFieldContext } from "./FormField";

// Props.
type InputProps = { render: (className?: string, path?: string, displayName?: string) => React.ReactNode };

// Component.
export default function Input(props: InputProps) {
  // Dependencies.
  const context = useContext(FormFieldContext);

  // Template.
  return props.render("form-control", context?.path, context?.displayName);
}

// NATSInternal.Frontend/NATSInternal.Vue/src/components/form/Input.vue
<script setup lang="ts">
import { computed, inject } from "vue";

// Child component.
import { FormFieldProvidePayloadKey } from "./FormField.vue";

// Dependencies.
const formFieldPayload = inject(FormFieldProvidePayloadKey);

// Slot payload.
const slotPayload = computed(() => ({
  className: "form-control",
  path: formFieldPayload?.path,
  displayName: formFieldPayload?.displayName
}));
</script>

<template>
  <slot v-bind="slotPayload"></slot>
</template>
