// NATSInternal.Frontend/NATSInternal.React/src/components/form/SelectInput.tsx
import React from "react";
import { joinClassName } from "@/helpers";

// Child component.
import Input from "./Input";
import { Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/react";
import { CheckIcon, ChevronDownIcon } from "@heroicons/react/24/outline";

// Props.
export type SelectInputOption = {
  value: string;
  displayName?: string;
};

export type SelectInputProps = {
  options: SelectInputOption[];
  value: string;
  onValueChanged(newValue: string): any;
  disabled?: boolean;
} & Omit<React.ComponentPropsWithoutRef<"div">, "children">;

// Component.
export default function SelectInput(props: SelectInputProps): React.ReactNode {
  // Template.
  function renderInput(className?: string, path?: string) {
    return (
      <Menu>
        <input type="hidden" name={path} id={props.id} />

        <MenuButton className={joinClassName(
          className,
          props.className,
          "form-control text-start hover:cursor-pointer flex justify-between items-center pe-2",
          "data-open:border-blue-500 data-open:outline-blue-500"
        )}>
          <span>{props.options.find(option => option.value == props.value)?.displayName}</span>
          <ChevronDownIcon className="size-4 shrink-0" />
        </MenuButton>

        <MenuItems
          className={joinClassName(
            "bg-white/50 dark:bg-neutral-800/65 border border-black/25 dark:border-white/25 outline-none",
            "rounded-lg shadow-lg p-1.5 backdrop-blur-md origin-center",
            "w-(--button-width) [--anchor-gap:--spacing(1.5)] max-h-100 overflow-y-auto",
            "origin-center transition duration-200 ease-out data-closed:scale-95 data-closed:opacity-0"
          )}
          anchor="bottom start"
          modal={false}
          transition
        >
          {props.options.map((option, index) => (
            <MenuItem key={index}>
              <div
                className={joinClassName(
                  "flex items-center gap-2 cursor-pointer px-3 py-1 rounded-lg",
                  "data-focus:bg-blue-500 data-focus:text-white",
                  option.value !== props.value && "ps-9"
                )}
                onClick={() => props.onValueChanged(option.value)}
              >
                {option.value === props.value && (<CheckIcon className="size-4" />)}
                <span>{option.displayName ?? option.value}</span>
              </div>
            </MenuItem>
          ))}
        </MenuItems>
      </Menu>
    );
  }

  return <Input render={renderInput} />;
}

// NATSInternal.Frontend/NATSInternal.Vue/src/components/form/SelectInput.vue
<script lang="ts">
export type SelectInputOption = {
  value: string;
  displayName?: string;
};
</script>

<script setup lang="ts">
// Child components.
import Input from "./Input.vue";
import { Menu, MenuButton, MenuItem, MenuItems } from "@headlessui/vue";
import { CheckIcon } from "@heroicons/vue/24/outline";

// Props and models.
const props = defineProps<{
  options: SelectInputOption[];
  disabled?: boolean;
}>();

const model = defineModel<string>({ required: true });

// Computed.
const computeInputId = (path?: string) => path?.replaceAll(".", "__");
</script>

<template>
  <Input v-slot="{ path }">
    <Menu>
      <input type="hidden" v-bind:name="path" v-bind:id="computeInputId(path)" />

      <MenuButton class="menu-button">
        {{ props.options.find(option => option.value)?.displayName }}
      </MenuButton>

      <MenuItems class="menu-items" :modal="false" anchor="bottom start" transition>
        <MenuItem
          v-for="option, index in options"
          v-bindclass="[`menu-item`, option.value !== model && `ps-9`]"
          v-bindkey="index"
          v-on:click="model = option.value"
          as="div"
        >
          <CheckIcon v-if="option.value === model" class="size-4" />
          <span>{{ option.displayName ?? option.value }}</span>
        </MenuItem>
      </MenuItems>
      
    </Menu>
  </Input>
</template>

<style scoped>
.menu-button {
  @apply 
    form-control text-start hover:cursor-pointer
    data-open:border-blue-500 data-open:outline-blue-500
}

.menu-items {
  @apply
    bg-white/50 dark:bg-neutral-800/65 border border-black/25 dark:border-white/25 outline-none
    rounded-lg shadow-lg p-1.5 backdrop-blur-md
    w-(--button-width) [--anchor-gap:--spacing(1.5)] max-h-100 overflow-y-auto
    origin-center transition duration-200 ease-out data-closed:scale-95 data-closed:opacity-0
}

.menu-item {
  @apply
    flex items-center gap-2 cursor-pointer px-3 py-1 rounded-lg
    data-focus:bg-blue-500 data-focus:text-white;
}
</style>
