// NATSInternal.Frontend/NATSInternal.Vue/src/components/ui/paginator/Paginator.vue
<script lang="ts">
import type { InjectionKey, Ref } from "vue";
import type { PaginationRange } from "@/helpers";

type PaginationRanges = {
  smScreen: PaginationRange,
  xsScreen: PaginationRange,
};

type PaginatorProvidePayload = {
  currentPage: Ref<number>;
  paginationRanges: Ref<PaginationRanges>;
  getClassName?(currentPage: number, isActive: boolean): string | undefined;
};
export const PaginatorProvidePayloadKey: InjectionKey<PaginatorProvidePayload> = Symbol("paginator-provide-payload");
</script>

<script setup lang="ts">
import { computed, provide } from "vue";
import { usePaginationHelper } from "@/helpers";

// Dependencies.
const { getPaginationRange } = usePaginationHelper();

// Props, emits and model.
const props = defineProps<{
  pageCount: number,
  getPageButtonClassName?(currentPage: number, isActive: boolean): string | undefined;
}>();

const model = defineModel<number>({ required: true });

// Computed.
const paginationRanges = computed<PaginationRanges>(() => ({
  smScreen: getPaginationRange({
    currentPage: model.value,
    pageCount: props.pageCount,
    visibleButtons: 5
  }),
  xsScreen: getPaginationRange({
    currentPage: model.value,
    pageCount: props.pageCount,
    visibleButtons: 3
  }),
}));

const pages = computed<number[]>(() => {
  const startingPage = paginationRanges.value.smScreen.startingPage;
  const endingPage = paginationRanges.value.smScreen.endingPage;
  const arrayLength = endingPage - (startingPage - 1);

  return Array.from({ length: arrayLength }, (_, index) => index + startingPage);
});

const isPageExceedingXsScreenRange = (page: number) => {
  return page < paginationRanges.value.xsScreen.startingPage || page > paginationRanges.value.xsScreen.endingPage;
};

const isPageExceedingSmScreenRange = (page: number) => {
  return page < paginationRanges.value.smScreen.startingPage || page > paginationRanges.value.smScreen.endingPage;
};

const computeButtonClassName = (page: number, isSeparatedButton: boolean = false): string => {
  const names: (string | false | undefined)[] = [
    "btn min-w-8.5",
    (isSeparatedButton && isPageExceedingXsScreenRange(page)) && "hidden sm:flex",
    props.getPageButtonClassName?.(page, model.value === page)
  ];

  return names.filter(n => n).join(" ");
};

// Callbacks.
const handlePageButtonClick = (page: number): void => {
  model.value = page;
};

// Provide.
provide(PaginatorProvidePayloadKey, {
  currentPage: model,
  paginationRanges,
  getClassName: props.getPageButtonClassName
});
</script>

<template>
  <div class="flex flex-row justify-center gap-2">
    <!-- Separated first page button -->
    <template v-if="isPageExceedingSmScreenRange(1)">
      <div :class="[`flex gap-2`, !isPageExceedingXsScreenRange(1) && `hidden`]">
        <button type="button" :class="computeButtonClassName(1)" @click="handlePageButtonClick(1)">
          {{ 1 }}
        </button>
        <span>...</span>
      </div>
    </template>

    <template v-for="page in pages" :key="page">
      <button type="button" :class="computeButtonClassName" @click="handlePageButtonClick(page)">
        {{ page }}
      </button>
    </template>

    <!-- Separated last page button -->
    <template v-if="isPageExceedingSmScreenRange(pageCount)">
      <div :class="[`flex gap-2`, !isPageExceedingXsScreenRange(pageCount) && `hidden`]">
        <span>...</span>
        <button
          type="button"
          :class="computeButtonClassName(pageCount)"
          @click="handlePageButtonClick(pageCount)"
        >
          {{ pageCount }}
        </button>
      </div>
    </template>
  </div>
</template>

// NATSInternal.Frontend/NATSInternal.React/src/components/ui/Paginator.tsx
import React, { useMemo } from "react";
import { usePaginationHelper, useTsxHelper, type PaginationRange } from "@/helpers";

// Child components.
import { Button } from ".";

// Types.
type PaginationRanges = {
  smScreen: PaginationRange,
  xsScreen: PaginationRange,
};

export type PaginatorProps = {
  page: number;
  pageCount: number;
  onPageChanged: (page: number) => any;
  getPageButtonClassName?: (page: number, isActive: boolean) => string | null | undefined;
} & React.ComponentPropsWithoutRef<"div">;

export default function Paginator(props: PaginatorProps): React.ReactNode {
  // Props.
  const {
    page: currentPage,
    pageCount,
    onPageChanged,
    className,
    getPageButtonClassName,
    ...domProps
  } = props;

  // Dependencies.
  const { getPaginationRange } = usePaginationHelper();
  const { joinClassName } = useTsxHelper();

  // Computed.
  const paginationRanges: PaginationRanges = useMemo(() => ({
    smScreen: getPaginationRange({
      currentPage,
      pageCount,
      visibleButtons: 5
    }),
    xsScreen: getPaginationRange({
      currentPage,
      pageCount,
      visibleButtons: 3
    }),
  }), [currentPage, pageCount]);

  const isPageExceedingXsScreenRange = (page: number) => {
    return page < paginationRanges.xsScreen.startingPage || page > paginationRanges.xsScreen.endingPage;
  };

  const isPageExceedingSmScreenRange = (page: number) => {
    return page < paginationRanges.smScreen.startingPage || page > paginationRanges.smScreen.endingPage;
  };

  // Callbacks.
  const handlePageButtonClick = (buttonPage: number): void => {
    props.onPageChanged(buttonPage);
  };

  // Template.
  if (pageCount <= 1) {
    return null;
  }

  const renderPageWithNumberButtons = (): React.ReactNode[] => {
    const startingPage = paginationRanges.smScreen.startingPage;
    const endingPage = paginationRanges.smScreen.endingPage;
    const arrayLength = endingPage - (startingPage - 1);

    return Array.from({ length: arrayLength }, (_, index) => index + startingPage).map(page => (
      <Button
        className={joinClassName(
          "min-w-8.5",
          isPageExceedingXsScreenRange(page) && "hidden sm:flex",
          getPageButtonClassName?.(pageCount, page === currentPage)
        )}
        onClick={() => handlePageButtonClick(page)}
        key={page}
      >
        {page}
      </Button>
    ));
  };

  return (
    <div {...domProps} className={joinClassName(className, "flex flex-row justify-center gap-2")}>
      {isPageExceedingSmScreenRange(1) && (
        <div className={joinClassName(
          "flex gap-2",
          !isPageExceedingXsScreenRange(1) && "hidden"
        )}>
          <Button
            className={joinClassName(
              "btn min-w-8.5",
              getPageButtonClassName?.(1, currentPage === 1))}
            onClick={() => handlePageButtonClick(1)}
          >
            {1}
          </Button>
          <span>...</span>
        </div>
      )}
      {renderPageWithNumberButtons()}
      {isPageExceedingSmScreenRange(pageCount) && (
        <div className={joinClassName(
          "flex gap-2",
          !isPageExceedingXsScreenRange(pageCount) && "hidden"
        )}>
          <span>...</span>
          <Button
            className={joinClassName(
              "btn min-w-8.5",
              getPageButtonClassName?.(pageCount, currentPage === pageCount))}
            onClick={() => handlePageButtonClick(pageCount)}
          >
            {pageCount}
          </Button>
        </div>
      )}
    </div>
  );
};
