// NATSInternal.Frontend/NATSInternal.Vue/src/components/layouts/navigationBar/NavigationBar.vue
<script setup lang="ts">
import { reactive, computed, onMounted, onUnmounted, watch, useTemplateRef } from "vue";
import { useNavigationBarStore } from "@/stores";

// Child components.
import NavigationBarItem from "./NavigationBarItem.vue";
import {
  HomeIcon as HomeOutlineIcon,
  UserCircleIcon as CustomerOutlineIcon,
  ArchiveBoxIcon as ProductOutlineIcon,
  TruckIcon as SupplyOutlineIcon,
  ShoppingCartIcon as OrderOutlineIcon,
  CurrencyDollarIcon as DebtOutlineIcon,
  CreditCardIcon as ExpenseOutlineIcon,
  ChartPieIcon as ReportOutlineIcon,
  IdentificationIcon as UserOutlineIcon } from "@heroicons/vue/24/outline";
import {
  HomeIcon as HomeSolidIcon,
  UserCircleIcon as CustomerSolidIcon,
  ArchiveBoxIcon as ProductSolidIcon,
  TruckIcon as SupplySolidIcon,
  ShoppingCartIcon as OrderSolidIcon,
  CurrencyDollarIcon as DebtSolidIcon,
  CreditCardIcon as ExpenseSolidIcon,
  ChartPieIcon as ReportSolidIcon,
  IdentificationIcon as UserSolidIcon } from "@heroicons/vue/24/solid";

// Dependencies.
const navigationBarStore = useNavigationBarStore();

// States.
const navigationBarElementRef = useTemplateRef<HTMLElement>("navigationBarElementRef");
const states = reactive({
  activeItemName: null as string | null,
  shouldBlockPointerEvent: false
});

// Computed.
const className = computed<string | null>(() => {
  if (navigationBarStore.isExpanded) {
    return "expanded";
  }

  return null;
});

// Callbacks.
function handleDocumentClicked(event: PointerEvent): void {
  if (!navigationBarStore.isExpanded) {
    return;
  }

  if (navigationBarElementRef.value === (event.target as HTMLElement)) {
    navigationBarStore.collapse();
  }
}

// Life cycle hooks.
onMounted(() => document.addEventListener("click", handleDocumentClicked));
onUnmounted(() => document.removeEventListener("click", handleDocumentClicked));

// Watch.
watch(() => navigationBarStore.isExpanded, () => {
  if (navigationBarStore.isExpanded) {
    states.shouldBlockPointerEvent = true;
    setTimeout(() => states.shouldBlockPointerEvent = true, 200);
  }
});
</script>

<template>
  <nav id="navbar" v-bind:class="className" ref="navigationBarElementRef">
    <div id="navbar-container">
      <div id="navbar-item-list">
        <!-- Home -->
        <NavigationBarItem name="home" fallback-display-name="Trang chủ" v-slot="{ isActive }">
          <HomeSolidIcon v-if="isActive" />
          <HomeOutlineIcon v-else />
        </NavigationBarItem>

        <!-- Customer -->
        <NavigationBarItem name="customer" v-slot="{ isActive }">
          <CustomerSolidIcon v-if="isActive" />
          <CustomerOutlineIcon v-else />
        </NavigationBarItem>
        
        <!-- Product -->
        <NavigationBarItem name="product" v-slot="{ isActive }">
          <ProductSolidIcon v-if="isActive" />
          <ProductOutlineIcon v-else />
        </NavigationBarItem>

        <!-- Supply -->
        <NavigationBarItem name="supply" v-slot="{ isActive }">
          <SupplySolidIcon v-if="isActive" />
          <SupplyOutlineIcon v-else />
        </NavigationBarItem>

        <!-- Order -->
        <NavigationBarItem name="order" v-slot="{ isActive }">
          <OrderSolidIcon v-if="isActive" />
          <OrderOutlineIcon v-else />
        </NavigationBarItem>

        <!-- Debt -->
        <NavigationBarItem name="debt" v-slot="{ isActive }">
          <DebtSolidIcon v-if="isActive" />
          <DebtOutlineIcon v-else />
        </NavigationBarItem>
        
        <!-- Expense -->
        <NavigationBarItem name="expense" v-slot="{ isActive }">
          <ExpenseSolidIcon v-if="isActive" />
          <ExpenseOutlineIcon v-else />
        </NavigationBarItem>

        <!-- Report -->
        <NavigationBarItem name="report" fallback-display-name="Báo cáo" v-slot="{ isActive }">
          <ReportSolidIcon v-if="isActive" />
          <ReportOutlineIcon v-else />
        </NavigationBarItem>

        <!-- Report -->
        <NavigationBarItem name="user" v-slot="{ isActive }">
          <UserSolidIcon v-if="isActive" />
          <UserOutlineIcon v-else />
        </NavigationBarItem>
      </div>
    </div>
  </nav>
</template>

// NATSInternal.Frontend/NATSInternal.React/src/components/layouts/navigationBar/NavigationBar.tsx
import React, { useState, useRef, useEffect, createContext } from "react";
import { useLocation } from "react-router";
import { useScreenBreakpoints } from "@/hooks";
import { useNavigationBarStore } from "@/stores";
import { joinClassName, getHomeRoutePath, getCustomerListRoutePath } from "@/helpers";
import { getProductListRoutePath, getExpenseListRoutePath, getSupplyListRoutePath } from "@/helpers";
import { getOrderListRoutePath, getDebtOverviewRoutePath, getReportRoutePath, getUserListRoutePath } from "@/helpers";

// Child components.
import NavigationBarItem from "./NavigationBarItem";
import type { NavigationBarItemData } from "./NavigationBarItem";

import {
  HomeIcon as HomeOutlineIcon,
  UserCircleIcon as CustomerOutlineIcon,
  ArchiveBoxIcon as ProductOutlineIcon,
  TruckIcon as SupplyOutlineIcon,
  ShoppingCartIcon as OrderOutlineIcon,
  CurrencyDollarIcon as DebtOutlineIcon,
  CreditCardIcon as ExpenseOutlineIcon,
  ChartPieIcon as ReportOutlineIcon,
  IdentificationIcon as UserOutlineIcon } from "@heroicons/react/24/outline";
import {
  HomeIcon as HomeSolidIcon,
  UserCircleIcon as CustomerSolidIcon,
  ArchiveBoxIcon as ProductSolidIcon,
  TruckIcon as SupplySolidIcon,
  ShoppingCartIcon as OrderSolidIcon,
  CurrencyDollarIcon as DebtSolidIcon,
  CreditCardIcon as ExpenseSolidIcon,
  ChartPieIcon as ReportSolidIcon,
  IdentificationIcon as UserSolidIcon } from "@heroicons/react/24/solid";

// Context.
type NavigationBarContextPayload = { activeItemName: string | null; };
export const NavigationBarContext = createContext<NavigationBarContextPayload>({ activeItemName: null });

// Component.
export default function NavigationBar(): React.ReactNode {
  // Dependencies.
  const location = useLocation();
  const navigationBarStore = useNavigationBarStore();

  // States.
  const breakpoints = useScreenBreakpoints();
  const navigationBarElementRef = useRef<HTMLElement>(null!);
  const navigationBarContainerElementRef = useRef<HTMLDivElement>(null!);
  const [activeItemName, setActiveItemName] = useState<string | null>(null);
  const [shouldBlockPointerEvent, setShouldBlockPointerEvent] = useState<boolean>(false);

  // Effect.
  useEffect(() => {
    if (breakpoints.md) {
      navigationBarStore.collapse();
    }
  }, [breakpoints.md]);

  useEffect(() => {
    const handleClicked = (event: PointerEvent) => {
      if (!navigationBarStore.isExpanded) {
        return;
      }

      if (navigationBarElementRef.current === (event.target as HTMLElement)) {
        navigationBarStore.collapse();
      }
    };

    document.addEventListener("pointerdown", handleClicked);

    if (navigationBarStore.isExpanded) {
      document.documentElement.style.maxHeight = "100vh";
      document.documentElement.style.overflow = "hidden";
    } else {
      document.documentElement.removeAttribute("style");
    }

    return () => document.removeEventListener("pointerdown", handleClicked);
  }, [navigationBarStore.isExpanded]);

  useEffect(() => {
    for (const item of navigationBarItems) {
      if (location.pathname.startsWith(item.routePath)) {
        setActiveItemName(item.name);
      }
    }
  }, [location.pathname]);
  
  useEffect(() => {
    if (navigationBarStore.isExpanded) {
      setShouldBlockPointerEvent(true);
      setTimeout(() => setShouldBlockPointerEvent(false), 200);
    }
  }, [navigationBarStore.isExpanded]);

  // Template.
  return (
    <nav
      id="navbar"
      className={joinClassName(
        navigationBarStore.isExpanded && "expanded",
        shouldBlockPointerEvent && "pointer-events-none"
      )}
      ref={navigationBarElementRef}
    >
      <div id="navbar-container" ref={navigationBarContainerElementRef}>
        {/* Navigation links */}
        <div id="navbar-item-list">
          {navigationBarItems.map((item) => (
            <NavigationBarItem
              name={item.name}
              fallbackDisplayName={item.fallbackDisplayName}
              routePath={item.routePath}
              Icon={item.Icon}
              isActive={activeItemName === item.name}
              showLabel={navigationBarStore.isExpanded}
              onClick={navigationBarStore.collapse}
              key={item.name}
            />
          ))}
        </div>
      </div>
    </nav>
  );
}

// Static variables.
const navigationBarItems: NavigationBarItemData[] = [
  {
    name: "home",
    fallbackDisplayName: "Trang chủ",
    routePath: getHomeRoutePath(),
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? HomeSolidIcon : HomeOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
  {
    name: "customer",
    routePath: getCustomerListRoutePath(),
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? CustomerSolidIcon : CustomerOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
  {
    name: "product",
    routePath: getProductListRoutePath(),
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? ProductSolidIcon : ProductOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
  {
    name: "supply",
    routePath: getSupplyListRoutePath(),
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? SupplySolidIcon : SupplyOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
  {
    name: "order",
    routePath: getOrderListRoutePath(),
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? OrderSolidIcon : OrderOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
  {
    name: "debt",
    routePath: getDebtOverviewRoutePath(),
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? DebtSolidIcon : DebtOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
  {
    name: "expense",
    routePath: getExpenseListRoutePath(),
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? ExpenseSolidIcon : ExpenseOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
  {
    name: "report",
    routePath: getReportRoutePath(),
    fallbackDisplayName: "Báo cáo",
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? ReportSolidIcon : ReportOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
  {
    name: "user",
    routePath: getUserListRoutePath(),
    Icon: ({ isActive, className, title }) => {
      const Component = isActive ? UserSolidIcon : UserOutlineIcon;
      return <Component className={className} title={title} />;
    }
  },
];
