// NATSInternal.Frontend/NATSInternal.Vue/src/components/layouts/navigationBar/NavigationBarItem.vue
<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";
import { useNavigationBarStore } from "@/stores";
import { getDisplayName } from "@/metadata";

// Props and emits.
const props = defineProps<{
  name: string;
  fallbackDisplayName?: string;
}>();

const emit = defineEmits<{
  (event: "clicked"): void;
}>();

// Dependencies.
const navigationBarStore = useNavigationBarStore();

// Computed.
const displayName = computed<string | undefined>(() => getDisplayName(props.name) ?? props.fallbackDisplayName);
const isActive = computed<boolean>(() => {
  return navigationBarStore.activeItemName === props.name;
});
</script>

<template>
  <RouterLink v-bind:class="{ 'active': isActive }" v-bind:to="{ name }" v-on:click="emit('clicked')">
    <slot class="size-5" v-bind="{ isActive }"></slot>
    <span v-if="navigationBarStore.isExpanded" class="inline-block md:hidden lg:inline-block">
      {{ displayName }}
    </span>

    <div class="tooltip">
      {{ displayName }}
    </div>
  </RouterLink>
</template>

// NATSInternal.Frontend/NATSInternal.React/src/components/layouts/navigationBar/NavigationBarItem.tsx
import React, { useMemo } from "react";
import { Link } from "react-router";
import { getDisplayName } from "@/metadata";
import { joinClassName } from "@/helpers";

// Types.
export type NavigationBarItemData = {
  name: string;
  fallbackDisplayName?: string;
  routePath: string;
  Icon?: (props: { isActive: boolean, className?: string, title?: string }) => React.ReactNode;
};

export type NavigationBarItemProps = NavigationBarItemData & {
  isActive: boolean;
  showLabel: boolean;
  onClick(): any;
};

export default function NavigationBarItem({ Icon, ...props }: NavigationBarItemProps): React.ReactNode {
  // Dependencies.
  const displayName = useMemo<string | undefined>(() => getDisplayName(props.name) ?? props.fallbackDisplayName, []);

  // Template.
  return (
    <Link
      className={joinClassName(props.isActive && "active")}
      to={props.routePath}
      onClick={props.onClick}
    >
      {Icon && <Icon isActive={props.isActive} />}
      <span className="inline-block md:hidden lg:inline-block">
        {displayName}
      </span>

      <div className="tooltip">
        {displayName}
      </div>
    </Link>
  );
}
